config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items
    resources :users, only: [:show]
    resources :carts
    resources :line_items, only: [:create]
    resources :orders, only: [:show]

    post 'carts/:id/', to: 'carts#checkout', as: 'checkout'
  root 'items#index'

end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :items, through: :line_items
  has_many :line_items
  belongs_to :user


  def check_out
    self.line_items.each do |line_item|
      item = Item.find(line_item.item_id)
      item.inventory = item.inventory - line_item.quantity
      item.save
    end
    # binding.pry
    user.update(current_cart: nil)
    self.update(status: "submitted")
  end

  def total
    @items_total = []
    self.line_items.each do |item|
      @item = Item.find_by_id(item.item_id)
      @items_total << @item.price.to_f
    end
    cart_total = @items_total.inject(0){|sum, x| sum + x }
    @cart_total = cart_total.round(2)
    @cart_total
  end

  def add_item(next_item)
    @current_line_item = self.line_items.find_by_id(next_item)
    if @current_line_item
      @current_line_item.quantity += 1
      @current_line_item.save
    else
      @current_line_item = self.line_items.build(item_id: next_item)
    end
    @current_line_item
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
   @cart = Cart.find_by_id(params[:id])
 end

 def new
   @cart = Cart.new(params[:user_id])
 end

 def create
   @cart = Cart.create(params[:user_id])
 end

 def show
   @cart = Cart.find_by_id(current_user.current_cart_id)
   current_user.save
 end

 def checkout
   @cart = Cart.find(params[:id])
   @cart.check_out
   redirect_to cart_path(@cart)
 end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>

<% if notice %>
  <p><%= notice %></p>
<% end %>
<% @cart.line_items.each do |line_item| %>
  <p><%= link_to line_item.item.title, item_path(line_item.item) %> | <%= number_to_currency(line_item.item.price.to_f/100)  %> | Quantity: <%= @cart_item_quantity = line_item.quantity %> | <% if line_item.item.inventory < 5 %>
    <strong>There are only <%= line_item.item.inventory %> left in stock.</strong>
  <% end %> </p>
<% end %>
<p>Order total: <strong><%= number_to_currency(@cart.total/100 * @cart_item_quantity) %></strong> </p>

<%= button_to 'Checkout', checkout_path %>